sequenceDiagram

    actor Client
    participant TableController
    participant TableManager
    participant CustomerOrderSocketHandler
    participant CustomerLocationStore
    participant BehaviourAnalyzer

    Client ->>+ TableController: DequeueTableReservation(branchId, tableNumber)
    