classDiagram
    IException <|-- NotFoundException
    IException <|-- BadRequestException
    IException <|-- UnauthorizedException

    class IException {
        <<interface>>
        +string Message
        +int StatusCode
    }